/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assesments;

import Login.User;
import SQL.Connect;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deniss
 */
public class ResultsTable extends javax.swing.JFrame {
    User user = new User();
    TableRow[] tSet;
    private int counter1;
    public ResultsTable() {
       counter1 = 0;
        initComponents();
         CreateObjects();




        
        

//Setting this so that all programm wouldn't close on x click
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        //LOADING TABLE CONTENT:
    }
    public void CreateObjects(){
         //OBJECTS AND EXTANCIATIONS
        Connection con = Connect.ConnectDB();
        ResultSet rs = null;
        ResultSet rs1 = null;
        PreparedStatement pst = null;
        //BUT FIRST HAVE TO SET QUESTION NUMBER
        //CONNECTING TO DATABASE, THEN MAKING QUERY
     try {
        //Will change this latter to SELECT DISTINCT and from question tabje
        String sql = "SELECT * FROM Results";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        //HAD TO CREATE QQ OUT OF THIS METHOD
        rs1 = pst.executeQuery();
        while(rs1.next()){
            counter1 = counter1 +1;
        }
        tSet = new TableRow[counter1];
             for(int i = 0; i<counter1;i++){
                 rs.next();
            tSet[i] = new TableRow();
            tSet[i].setLogedUser(rs.getString("LogedUser"));
            tSet[i].setSubject(rs.getString("Subject"));
            tSet[i].setScore(rs.getString("Score"));
            tSet[i].setMaxScore(rs.getString("maxScore"));
            tSet[i].setNumberOfQuestions(rs.getString("NumberOfQuestions"));
            tSet[i].setAssesmentType(rs.getString("AssesmentType"));
            tSet[i].setDateAndTime(rs.getString("DateAndTime"));
            
     }
                  
    } catch (Exception e){
        JOptionPane.showMessageDialog(null, e);
            
    }

        
    }
    public void SetUser(){
        TfUser.setText("Assesments Results for User: " + user.getLogin());
    }
   public void setUser(User usr){
        this.user = usr;
        SetUser();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TfSubject = new javax.swing.JLabel();
        TfUser = new javax.swing.JLabel();
        BtnQuizResult = new javax.swing.JButton();
        BtnExamResult = new javax.swing.JButton();
        BtnAllResults = new javax.swing.JButton();
        BtnChoice = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        TfSubject.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        TfSubject.setText("Assesments Results:");
        jPanel1.add(TfSubject);
        TfSubject.setBounds(140, 20, 310, 40);

        TfUser.setText("Assesments Results for User: #####");
        jPanel1.add(TfUser);
        TfUser.setBounds(360, 460, 210, 30);

        BtnQuizResult.setText("Quizez results");
        BtnQuizResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQuizResultActionPerformed(evt);
            }
        });
        jPanel1.add(BtnQuizResult);
        BtnQuizResult.setBounds(10, 490, 120, 23);

        BtnExamResult.setText("Exam results");
        jPanel1.add(BtnExamResult);
        BtnExamResult.setBounds(150, 490, 120, 23);

        BtnAllResults.setText("All results");
        BtnAllResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllResultsActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAllResults);
        BtnAllResults.setBounds(280, 490, 110, 23);

        BtnChoice.setText("Assesments choices");
        BtnChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnChoiceActionPerformed(evt);
            }
        });
        jPanel1.add(BtnChoice);
        BtnChoice.setBounds(400, 490, 160, 23);

        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 70, 452, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnChoiceActionPerformed
         this.setVisible(false);
         AFrame myAFrame  = new AFrame();  
        myAFrame.setVisible(true);
        myAFrame.setSize(380, 370);
        myAFrame.setResizable(false);
        myAFrame.setUser(user);
    }//GEN-LAST:event_BtnChoiceActionPerformed

    private void BtnQuizResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQuizResultActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_BtnQuizResultActionPerformed

    private void BtnAllResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllResultsActionPerformed
 for(int i = 0; i<counter1;i++){
            System.out.println(tSet[i].getLogedUser());
            System.out.println(tSet[i].getSubject());
            System.out.println(tSet[i].getScore());
            System.out.println(tSet[i].getMaxScore());
            System.out.println(tSet[i].getNumberOfQuestions());
            System.out.println(tSet[i].getAssesmentType());
            System.out.println(tSet[i].getDateAndTime());
     }         // TODO add your handling code here:
    }//GEN-LAST:event_BtnAllResultsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultsTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAllResults;
    private javax.swing.JButton BtnChoice;
    private javax.swing.JButton BtnExamResult;
    private javax.swing.JButton BtnQuizResult;
    private javax.swing.JLabel TfSubject;
    private javax.swing.JLabel TfUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
